name: CI test

on:
  push:
    branches: [devel, staging]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Test env Node v.${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Run ESLint
        run: yarn lint
      - name: Run Typescript
        run: yarn tsc
      - name: Run Jest tests
        run: yarn jest